# Form implementation generated from reading ui file 'app/ui/modules/blender/b_launcher.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(854, 954)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        self.gridLayout_function = QtWidgets.QGridLayout()
        self.gridLayout_function.setObjectName("gridLayout_function")
        self.gridLayout_builderType = QtWidgets.QGridLayout()
        self.gridLayout_builderType.setObjectName("gridLayout_builderType")
        self.radioButton_builderType1 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_builderType1.setObjectName("radioButton_builderType1")
        self.gridLayout_builderType.addWidget(self.radioButton_builderType1, 2, 0, 1, 1)
        self.radioButton_builderType2 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_builderType2.setObjectName("radioButton_builderType2")
        self.gridLayout_builderType.addWidget(self.radioButton_builderType2, 2, 1, 1, 1)
        self.radioButton_builderType0 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_builderType0.setChecked(True)
        self.radioButton_builderType0.setAutoExclusive(False)
        self.radioButton_builderType0.setObjectName("radioButton_builderType0")
        self.gridLayout_builderType.addWidget(self.radioButton_builderType0, 1, 0, 1, 2)
        self.label_builderType = QtWidgets.QLabel(parent=Form)
        self.label_builderType.setObjectName("label_builderType")
        self.gridLayout_builderType.addWidget(self.label_builderType, 0, 0, 1, 2)
        self.gridLayout_function.addLayout(self.gridLayout_builderType, 2, 0, 1, 2)
        self.gridWidget_blenderPath = QtWidgets.QWidget(parent=Form)
        self.gridWidget_blenderPath.setStyleSheet("#gridWidget_blenderPath .QWidget {\n"
"background-color: White;\n"
"border: 2px solid black;\n"
"border-radius: 5%;\n"
"}\n"
"\n"
"#gridWidget_blenderPath .QLineEdit {\n"
"border: 1px solid black;\n"
"border-radius: 5%;\n"
"}\n"
"\n"
"#gridWidget_blenderPath .QToolButton {\n"
"border: none;\n"
"background-color:  black;\n"
"color: white;\n"
"border-radius: 5%;\n"
"padding: 2px;\n"
"}")
        self.gridWidget_blenderPath.setObjectName("gridWidget_blenderPath")
        self.gridLayout_blenderPath = QtWidgets.QGridLayout(self.gridWidget_blenderPath)
        self.gridLayout_blenderPath.setObjectName("gridLayout_blenderPath")
        self.lineEdit_blenderPath = QtWidgets.QLineEdit(parent=self.gridWidget_blenderPath)
        self.lineEdit_blenderPath.setStyleSheet("")
        self.lineEdit_blenderPath.setObjectName("lineEdit_blenderPath")
        self.gridLayout_blenderPath.addWidget(self.lineEdit_blenderPath, 1, 0, 1, 1)
        self.toolButton_blenderPath = QtWidgets.QToolButton(parent=self.gridWidget_blenderPath)
        self.toolButton_blenderPath.setObjectName("toolButton_blenderPath")
        self.gridLayout_blenderPath.addWidget(self.toolButton_blenderPath, 1, 1, 1, 1)
        self.label_blenderPath = QtWidgets.QLabel(parent=self.gridWidget_blenderPath)
        self.label_blenderPath.setObjectName("label_blenderPath")
        self.gridLayout_blenderPath.addWidget(self.label_blenderPath, 0, 0, 1, 2)
        self.gridLayout_function.addWidget(self.gridWidget_blenderPath, 0, 0, 1, 2)
        self.pushButton_upVersion = QtWidgets.QPushButton(parent=Form)
        self.pushButton_upVersion.setEnabled(True)
        self.pushButton_upVersion.setObjectName("pushButton_upVersion")
        self.gridLayout_function.addWidget(self.pushButton_upVersion, 7, 1, 1, 1)
        self.pushButton_batch = QtWidgets.QPushButton(parent=Form)
        self.pushButton_batch.setEnabled(False)
        self.pushButton_batch.setStyleSheet("")
        self.pushButton_batch.setCheckable(False)
        self.pushButton_batch.setObjectName("pushButton_batch")
        self.gridLayout_function.addWidget(self.pushButton_batch, 4, 1, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(parent=Form)
        self.pushButton_open.setStyleSheet(".QPushButton {\n"
"    border: none;\n"
"    background-color: black;\n"
"    border-radius: 5%;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #333333;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
".QPushButton:pressed {\n"
"    background-color: #666666;\n"
"    color: #e0e0e0;\n"
"    padding: 5px 4px 3px 4px;\n"
"}")
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_function.addWidget(self.pushButton_open, 9, 0, 1, 2)
        self.checkBox_batch = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_batch.setObjectName("checkBox_batch")
        self.gridLayout_function.addWidget(self.checkBox_batch, 4, 0, 1, 1)
        self.pushButton_upMaster = QtWidgets.QPushButton(parent=Form)
        self.pushButton_upMaster.setObjectName("pushButton_upMaster")
        self.gridLayout_function.addWidget(self.pushButton_upMaster, 7, 0, 1, 1)
        self.pushButton_unlock = QtWidgets.QPushButton(parent=Form)
        self.pushButton_unlock.setObjectName("pushButton_unlock")
        self.gridLayout_function.addWidget(self.pushButton_unlock, 8, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_function.addItem(spacerItem, 1, 0, 1, 2)
        self.pushButton_replace = QtWidgets.QPushButton(parent=Form)
        self.pushButton_replace.setStyleSheet(".QPushButton {\n"
"    border: none;\n"
"    background-color: red;\n"
"    border-radius: 5%;\n"
"    color: white;\n"
"    padding: 4px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #ff3333;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
".QPushButton:pressed {\n"
"    background-color: #cc0000;\n"
"    color: #f0f0f0;\n"
"    padding: 5px 4px 3px 4px;\n"
"}")
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.gridLayout_function.addWidget(self.pushButton_replace, 6, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_function.addItem(spacerItem1, 3, 0, 1, 2)
        self.gridLayout_main.addLayout(self.gridLayout_function, 1, 1, 1, 1)
        self.gridWidget_metadata = QtWidgets.QWidget(parent=Form)
        self.gridWidget_metadata.setStyleSheet(".QTableView {\n"
"border-radius: 5%;\n"
"border: 1px solid black;\n"
"}")
        self.gridWidget_metadata.setObjectName("gridWidget_metadata")
        self.gridLayout_metadata = QtWidgets.QGridLayout(self.gridWidget_metadata)
        self.gridLayout_metadata.setObjectName("gridLayout_metadata")
        self.label_metadata = QtWidgets.QLabel(parent=self.gridWidget_metadata)
        self.label_metadata.setObjectName("label_metadata")
        self.gridLayout_metadata.addWidget(self.label_metadata, 0, 0, 1, 1)
        self.tableView_task = QtWidgets.QTableView(parent=self.gridWidget_metadata)
        self.tableView_task.setObjectName("tableView_task")
        self.gridLayout_metadata.addWidget(self.tableView_task, 3, 0, 1, 1)
        self.label_task = QtWidgets.QLabel(parent=self.gridWidget_metadata)
        self.label_task.setObjectName("label_task")
        self.gridLayout_metadata.addWidget(self.label_task, 2, 0, 1, 1)
        self.tableView_metadata = QtWidgets.QTableView(parent=self.gridWidget_metadata)
        self.tableView_metadata.setObjectName("tableView_metadata")
        self.gridLayout_metadata.addWidget(self.tableView_metadata, 1, 0, 1, 1)
        self.gridLayout_main.addWidget(self.gridWidget_metadata, 0, 2, 1, 1)
        self.verticalWidget_version = QtWidgets.QWidget(parent=Form)
        self.verticalWidget_version.setStyleSheet(".QListWidget {\n"
"border-radius: 5%;\n"
"border: 1px solid black;\n"
"}\n"
"")
        self.verticalWidget_version.setObjectName("verticalWidget_version")
        self.verticalLayout_version = QtWidgets.QVBoxLayout(self.verticalWidget_version)
        self.verticalLayout_version.setObjectName("verticalLayout_version")
        self.label_version = QtWidgets.QLabel(parent=self.verticalWidget_version)
        self.label_version.setObjectName("label_version")
        self.verticalLayout_version.addWidget(self.label_version)
        self.radioButton_showMaster = QtWidgets.QRadioButton(parent=self.verticalWidget_version)
        self.radioButton_showMaster.setObjectName("radioButton_showMaster")
        self.verticalLayout_version.addWidget(self.radioButton_showMaster)
        self.listWidget_version = QtWidgets.QListWidget(parent=self.verticalWidget_version)
        self.listWidget_version.setObjectName("listWidget_version")
        self.verticalLayout_version.addWidget(self.listWidget_version)
        self.gridLayout_main.addWidget(self.verticalWidget_version, 1, 2, 1, 1)
        self.verticalWidget_list = QtWidgets.QWidget(parent=Form)
        self.verticalWidget_list.setStyleSheet(".QListWidget {\n"
"border-radius: 5%;\n"
"border: 1px solid black;\n"
"}\n"
"\n"
".QLineEdit {\n"
"border-radius: 5%;\n"
"border: 1px solid black;\n"
"}\n"
"")
        self.verticalWidget_list.setObjectName("verticalWidget_list")
        self.verticalLayout_list = QtWidgets.QVBoxLayout(self.verticalWidget_list)
        self.verticalLayout_list.setObjectName("verticalLayout_list")
        self.lineEdit_list = QtWidgets.QLineEdit(parent=self.verticalWidget_list)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_list.setFont(font)
        self.lineEdit_list.setStatusTip("")
        self.lineEdit_list.setObjectName("lineEdit_list")
        self.verticalLayout_list.addWidget(self.lineEdit_list)
        self.listWidget_list = QtWidgets.QListWidget(parent=self.verticalWidget_list)
        self.listWidget_list.setObjectName("listWidget_list")
        self.verticalLayout_list.addWidget(self.listWidget_list)
        self.gridLayout_main.addWidget(self.verticalWidget_list, 0, 0, 2, 1)
        self.verticalWidget_search = QtWidgets.QWidget(parent=Form)
        self.verticalWidget_search.setStyleSheet("/* The main box */\n"
"QComboBox {\n"
"    border: 1px solid #3d3d3d;\n"
"    border-radius: 5px; /* macOS uses approx 5-6px */\n"
"    padding: 4px 10px 4px 10px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* The container for the arrow */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: none;\n"
"}\n"
"\n"
"/* The macOS Chevron (Simplified) */\n"
"QComboBox::down-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid #BBBBBB;\n"
"    margin-right: 8px;\n"
"}\n"
"")
        self.verticalWidget_search.setObjectName("verticalWidget_search")
        self.verticalLayout_search = QtWidgets.QVBoxLayout(self.verticalWidget_search)
        self.verticalLayout_search.setObjectName("verticalLayout_search")
        self.label = QtWidgets.QLabel(parent=self.verticalWidget_search)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_search.addWidget(self.label)
        self.verticalLayout_department = QtWidgets.QVBoxLayout()
        self.verticalLayout_department.setObjectName("verticalLayout_department")
        self.label_department = QtWidgets.QLabel(parent=self.verticalWidget_search)
        self.label_department.setObjectName("label_department")
        self.verticalLayout_department.addWidget(self.label_department)
        self.comboBox_department = QtWidgets.QComboBox(parent=self.verticalWidget_search)
        self.comboBox_department.setObjectName("comboBox_department")
        self.verticalLayout_department.addWidget(self.comboBox_department)
        self.verticalLayout_search.addLayout(self.verticalLayout_department)
        self.verticalLayout_project = QtWidgets.QVBoxLayout()
        self.verticalLayout_project.setObjectName("verticalLayout_project")
        self.label_project = QtWidgets.QLabel(parent=self.verticalWidget_search)
        self.label_project.setObjectName("label_project")
        self.verticalLayout_project.addWidget(self.label_project)
        self.comboBox_project = QtWidgets.QComboBox(parent=self.verticalWidget_search)
        self.comboBox_project.setObjectName("comboBox_project")
        self.verticalLayout_project.addWidget(self.comboBox_project)
        self.verticalLayout_search.addLayout(self.verticalLayout_project)
        self.verticalLayout_entity = QtWidgets.QVBoxLayout()
        self.verticalLayout_entity.setObjectName("verticalLayout_entity")
        self.label_entity = QtWidgets.QLabel(parent=self.verticalWidget_search)
        self.label_entity.setObjectName("label_entity")
        self.verticalLayout_entity.addWidget(self.label_entity)
        self.comboBox_entity = QtWidgets.QComboBox(parent=self.verticalWidget_search)
        self.comboBox_entity.setObjectName("comboBox_entity")
        self.verticalLayout_entity.addWidget(self.comboBox_entity)
        self.verticalLayout_search.addLayout(self.verticalLayout_entity)
        self.verticalLayout_episode = QtWidgets.QVBoxLayout()
        self.verticalLayout_episode.setObjectName("verticalLayout_episode")
        self.label_episode = QtWidgets.QLabel(parent=self.verticalWidget_search)
        self.label_episode.setObjectName("label_episode")
        self.verticalLayout_episode.addWidget(self.label_episode)
        self.comboBox_episode = QtWidgets.QComboBox(parent=self.verticalWidget_search)
        self.comboBox_episode.setObjectName("comboBox_episode")
        self.verticalLayout_episode.addWidget(self.comboBox_episode)
        self.verticalLayout_search.addLayout(self.verticalLayout_episode)
        self.verticalLayout_type = QtWidgets.QVBoxLayout()
        self.verticalLayout_type.setObjectName("verticalLayout_type")
        self.label_type = QtWidgets.QLabel(parent=self.verticalWidget_search)
        self.label_type.setObjectName("label_type")
        self.verticalLayout_type.addWidget(self.label_type)
        self.comboBox_type = QtWidgets.QComboBox(parent=self.verticalWidget_search)
        self.comboBox_type.setObjectName("comboBox_type")
        self.verticalLayout_type.addWidget(self.comboBox_type)
        self.verticalLayout_search.addLayout(self.verticalLayout_type)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_search.addItem(spacerItem2)
        self.gridLayout_main.addWidget(self.verticalWidget_search, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_main, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_builderType1.setText(_translate("Form", "Previous"))
        self.radioButton_builderType2.setText(_translate("Form", "Next"))
        self.radioButton_builderType0.setText(_translate("Form", "Default"))
        self.label_builderType.setText(_translate("Form", "Builder Type"))
        self.toolButton_blenderPath.setText(_translate("Form", "Locate"))
        self.label_blenderPath.setText(_translate("Form", "Blender"))
        self.pushButton_upVersion.setText(_translate("Form", "UpVersion"))
        self.pushButton_batch.setText(_translate("Form", "Start Batch"))
        self.pushButton_open.setText(_translate("Form", "Open"))
        self.checkBox_batch.setText(_translate("Form", "Batch"))
        self.pushButton_upMaster.setText(_translate("Form", "UpMaster"))
        self.pushButton_unlock.setText(_translate("Form", "Unlock"))
        self.pushButton_replace.setText(_translate("Form", "Replace"))
        self.label_metadata.setText(_translate("Form", "Metadata"))
        self.label_task.setText(_translate("Form", "Task"))
        self.label_version.setText(_translate("Form", "Version"))
        self.radioButton_showMaster.setText(_translate("Form", "Show Master"))
        self.lineEdit_list.setToolTip(_translate("Form", "Search Shot/Asset"))
        self.lineEdit_list.setPlaceholderText(_translate("Form", "Search Shot"))
        self.label.setText(_translate("Form", "Select First"))
        self.label_department.setText(_translate("Form", "Department"))
        self.comboBox_department.setPlaceholderText(_translate("Form", "-- Select Department --"))
        self.label_project.setText(_translate("Form", "Project"))
        self.comboBox_project.setPlaceholderText(_translate("Form", "-- Select Project --"))
        self.label_entity.setText(_translate("Form", "Entity"))
        self.comboBox_entity.setPlaceholderText(_translate("Form", "-- Select Entity --"))
        self.label_episode.setText(_translate("Form", "Episode"))
        self.comboBox_episode.setPlaceholderText(_translate("Form", "-- Select Episode --"))
        self.label_type.setText(_translate("Form", "Type"))
        self.comboBox_type.setPlaceholderText(_translate("Form", "-- Select Type --"))
